export const COMPANY: any = {
	1: {
		Id: 1,
		name: "Teva Pharmaceuticals USA Inc",
		country: "Czech Republic",
		address: "74 Banding Center",
		seqNo: 0,
		companyUrl: "jigsy-teva.com",
		products: [
			{
				Id: 41,
				brandName: "LBEL",
				genericName: "TITANIUM DIOXIDE, OXYBENZONE, ZINC OXIDE, and OCTINOXATE",
				imageUrl: "http://dummyimage.com/185x100.png/ff4444/ffffff",
				seqNo: 1,
			},
			{
				Id: 42,
				brandName: "Testosterone",
				genericName: "Testosterone,",
				imageUrl: "http://dummyimage.com/182x100.png/5fa2dd/ffffff",
				seqNo: 2,
			},
			{
				Id: 43,
				brandName: "Minocycline Hydrochloride",
				genericName: "Minocycline Hydrochloride",
				imageUrl: "http://dummyimage.com/115x100.png/5fa2dd/ffffff",
				seqNo: 3,
			},
			{
				Id: 44,
				brandName: "Demeclocycline Hydrochloride",
				genericName: "Demeclocycline Hydrochloride",
				imageUrl: "http://dummyimage.com/128x100.png/5fa2dd/ffffff",
				seqNo: 4,
			},
		],
	},

	2: {
		Id: 2,
		name: "Pro Chem, Incorporated",
		country: "Afghanistan",
		address: "45 Donald Way",
		seqNo: 1,
		companyUrl: "dailymotion.com",
		products: [
			{
				Id: 45,
				brandName: "Mycobutin",
				genericName: "rifabutin",
				imageUrl: "http://dummyimage.com/178x100.png/dddddd/000000",
				seqNo: 5,
			},
			{
				Id: 46,
				brandName: "Venapro",
				genericName: "Aesculus hippocastanum, Muriaticum acidum, Ratanhia,",
				imageUrl: "http://dummyimage.com/112x100.png/dddddd/000000",
				seqNo: 6,
			},
			{
				Id: 47,
				brandName: "CalmaFX",
				genericName: "MENTHOL, CALAMINE, ZINC OXIDE",
				imageUrl: "http://dummyimage.com/112x100.png/ff4444/ffffff",
				seqNo: 7,
			},
			{
				Id: 48,
				brandName: "Olanzapine",
				genericName: "Olanzapine",
				imageUrl: "http://dummyimage.com/247x100.png/5fa2dd/ffffff",
				seqNo: 8,
			},
		],
	},
	3: {
		Id: 3,
		name: "L'Oreal USA Products Inc",
		country: "Czech Republic",
		address: "2510 Grasskamp Point",
		seqNo: 2,
		companyUrl: "noaa.gov",
		products: [
			{
				id: 49,
				brandName: "NEUROSPORA INTERMEDIA",
				genericName: "NEUROSPORA INTERMEDIA",
				imageUrl: "http://merriam-webster.com/rutrum.js?lacus",
				seqNo: 9,
			},
			{
				id: 50,
				brandName: "Premier Value",
				genericName: "Miconazole Nitrate",
				imageUrl:
					"https://irs.gov/sed/tincidunt/eu/felis/fusce/posuere/felis.xml",
				seqNo: 10,
			},
			{
				id: 51,
				brandName: "FEXMID",
				genericName: "CYCLOBENZAPRINE HYDROCHLORIDE",
				imageUrl: "http://smugmug.com/metus/aenean.html?nisl=posuere",
				seqNo: 11,
			},
			{
				id: 52,
				brandName: "topcare day time cold and flu relief",
				genericName: "acetaminophen, dextromethorphan Hbr, Phenylephrine HCl",
				imageUrl:
					"https://e-recht24.de/libero.jsp?justo=eget&aliquam=tincidunt&quis",
				seqNo: 12,
			},
		],
	},
	4: {
		Id: 4,
		name: "Bedford Laboratories",
		country: "China",
		address: "85277 Waxwing Circle",
		seqNo: 3,
		companyUrl: "tripadvisor.com",
		products: [
			{
				id: 53,
				brandName: "Cefdinir",
				genericName: "Cefdinir",
				imageUrl: "http://live.com/felis/sed/interdum/venenatis.js",
				seqNo: 13,
			},
			{
				id: 54,
				brandName: "Crest Complete Multi-Benefit",
				genericName: "Sodium Fluoride",
				imageUrl: "https://arizona.edu/urna/ut.jsp?con=primis",
				seqNo: 14,
			},
			{
				id: 55,
				brandName: "CARMEX Lime twist BROAD SPECTRUM SPF 15 SUNSCREEN",
				genericName: "AVOBENZONE, OCTISALATE, HOMOSALATE, OCTOCRYLENE",
				imageUrl: "http://biblegateway.com/augue/vestibulum.jsonconvallis",
				seqNo: 15,
			},
			{
				id: 56,
				brandName: "Actos",
				genericName: "pioglitazone hydrochloride",
				imageUrl: "http://chronoengine.com/eget/vulputate/ut/ultrices/",
				seqNo: 16,
			},
		],
	},
};

export const USERS = {
	1: {
		id: 1,
		email: "madukaololo@hotmail.com",
		plainTextPassword: "test",
		passwordSalt: "o61TA7yaJIsa",
		pictureUrl: "http://nationalgeographic.com",
		isAdmin: false,
	},
	2: {
		id: 2,
		email: "okeke4you@gmail.com",
		plainTextPassword: "admin",
		passwordSalt: "NydKRjIh4T4X",
		pictureUrl: "https://seattletimes.com",
		isAdmin: true,
	},
};
